version: "3.8"
services:
  db:
    image: postgres:11.5
    container_name: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: beer-app
      POSTGRES_PASSWORD: beer-app
      POSTGRES_DB: beer-app
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
